"use client"
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/Components/Header";
import SidePanel from "@/Components/SidePanel";
import LowHeader from "@/Components/LowHeader";
import { useState } from "react";
import ProfileSidePanel from "@/Components/ProfileSidePanel";
import SearchPopup from "@/Components/SearchPopup";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const [sideBarToggle,setSideBarToggle] = useState(false);
  const [profilePanelToggle,setProfilePanelToggle] = useState(false);
  const [searchPopupToggle,setSearchPopupToggle] = useState(false);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="sticky top-0 z-50">
          <Header setSearchPopup={setSearchPopupToggle} profilePanel={profilePanelToggle} setProfilePanel={setProfilePanelToggle} sideBarToggle={sideBarToggle} setSideBarToggle={setSideBarToggle}/>
        </div>
      <SidePanel sideBarToggle={sideBarToggle} setSideBarToggle={setSideBarToggle} />
       <ProfileSidePanel profilePanelToggle={profilePanelToggle} setProfilePanelToggle={setProfilePanelToggle}/>
        {searchPopupToggle?<SearchPopup setSearchPopup={setSearchPopupToggle} />:null}
      
        <LowHeader setSearchPopup={setSearchPopupToggle} />
        {children}
      </body>
    </html>
  );
}
